bot:
  prefix: "~"
  extensions:
  - bot.cogs.reload
  - bot.cogs.debug
  - bot.cogs.suggestions
  - bot.cogs.meeting_notes
  # - bot.cogs.log
  # - bot.cogs.pin
  admins:
  # Gehock#9200
  - 150625032656125952

guild:
  roles:
    # staff @ Zeus Operations
    staff: 287726126917222402

cogs:
  # log:
  #   channels:
  #     delete_log: 0
  # pin:
  #   channel: 0
  #   keyword: SUGGESTION
  suggestions:
    channels:
    - suggestions: 360434525798531084
      discussion: null
    - suggestions: 810636847780331531
      discussion: null
    reactions:
    # \N{HEAVY PLUS SIGN}
    - "\u2795"
    # \N{HEAVY MINUS SIGN}
    - "\u2796"
    # \N{WAVY DASH}
    - "\u3030"
    keyword: '**'
    image_keyword: 'IMG:'
    # Replaced variables:
    #   {0}: the name of the suggestion channel
    #   {1}: the original message
    #   {2}: the image keyword
    # Message gets folded to a single line, leave a blank line to create a
    # line break
    message: >
      Invalid format in `#{0}`, please post your suggestion in a single message
      and follow the pinned template (press Shift+Enter for a new line). The
      message has to start with a `**bolded**` title. If you already posted a
      suggestion, please edit the original message instead of sending multiple
      messages.

      ```

      {1}

      ```

      If this is an image with a caption that wasn't detected
      correctly, please prefix the message with `{2}`
    thread_message: >
      To comment on suggestions, please create a thread on the suggestion message.
    discussion_channel: False
    use_threads: True
  meetingnotes:
    keyword: '**'
    divider_regex: '^\*\*Suggestions for ([A-Z][a-z]+) below\*\*$'
    divider: '**Suggestions for {0} below**'
    date_locale: en_US.UTF-8
    channels:
      suggestions: 360434525798531084
    save_gist: True
