bot:
  prefix: "!"
  extensions:
    - bot.cogs.reload
    - bot.cogs.log
    - bot.cogs.pin

guild:
  roles:
    staff: 805118172524576788
  channels:
    delete_log: 804707231077629962

cogs:
  pin:
    channel: 804707231077629962
    keyword: SUGGESTION
