bot:
  prefix: "!"
  extensions:
  - bot.cogs.reload
  - bot.cogs.suggestions
  # - bot.cogs.log
  # - bot.cogs.pin

guild:
  roles:
    staff: 805118172524576788

cogs:
  log:
    channels:
      delete_log: 804707231077629962
  pin:
    channel: 804707231077629962
    keyword: SUGGESTION
  suggestions:
    channels:
      - suggestions: 804707231077629962
        discussion: 809132751226798143
      - suggestions: 809802914373304420
        discussion: 809802939497054208
    reactions:
      # \N{HEAVY PLUS SIGN}
      - "\u2795"
      # \N{HEAVY MINUS SIGN}
      - "\u2796"
      # \N{WAVY DASH}
      - "\u3030"
    keyword: '**'
    # {0} gets replaced by the name of the channel
    # {1} gets replaced by the original message
    message: >
      Invalid format in `#{0}`, please post your suggestion in a single message
      and follow the pinned template (press Shift+Enter for a new line). The
      message has to start with a `**bolded**` title. If you already posted a
      suggestion, please edit the original message instead of sending multiple
      messages.
      ```
      {1}
      ```
